name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        compiler: [gcc, clang]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: build
      env:
        CC: ${{ matrix.compiler }}
      run: make

  memcheck_valgrind:
    strategy:
      fail-fast: false
      matrix:
        compiler: [gcc, clang]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install valgrind
      run: |
        sudo apt update
        sudo apt install valgrind
    - name: build
      env:
        CC: ${{ matrix.compiler }}
      run: make test
    - name: Run valgrind
      run: make memcheck
